import { GetMarketResponse } from "@/types/market/marketType";

export const publicTenders: GetMarketResponse[] = [
  {
    id: "tender-1",
    title: "Fourniture de consommables et produits d'entretien",
    description:
      "Achat de produits d'entretien, consommables d'hygiene et fournitures associees pour plusieurs etablissements scolaires.",
    footerDescription:
      "Achat de produits d'entretien, consommables d'hygiene et fournitures associees pour plusieurs etablissements scolaires.",
    location: "Koungou, Mayotte",
    limitDate: "2026-05-23T00:00:00Z",
    displayPrice: "70 000 EUR HT estimatif",
    price: 70000,
    lot: 2,
    duration: 12,
    reference: "DATA-2026-2019",
    sigleReference: "DATA-2019",
    buyer: "Etablissement scolaire",
    avisLink: "https://www.data.gouv.fr/",
    typeMarket: "Fournitures",
    tags: ["consommables", "produits", "entretien", "hygiene"],
    createdAt: "2026-04-12T08:00:00Z",
  },
  {
    id: "tender-2",
    title: "Entretien des espaces verts et debroussaillage",
    description:
      "Prestations d'entretien des espaces verts, debroussaillage et evacuation des dechets verts.",
    footerDescription:
      "Prestations d'entretien des espaces verts, debroussaillage et evacuation des dechets verts.",
    location: "Petite-Terre, Mayotte",
    limitDate: "2026-06-25T00:00:00Z",
    displayPrice: "60 000 EUR HT estimatif",
    price: 60000,
    lot: 1,
    duration: 24,
    reference: "DATA-2026-2028",
    sigleReference: "DATA-2028",
    buyer: "Commune de Mayotte",
    avisLink: "https://www.data.gouv.fr/",
    typeMarket: "Espaces verts",
    tags: ["espaces verts, debroussaillage, collecte"],
    createdAt: "2026-04-20T08:00:00Z",
  },
  {
    id: "tender-3",
    title: "Travaux de renovation de batiments publics",
    description:
      "Travaux de renovation interieure, reprise de second oeuvre, menuiserie, peinture et petites reparations.",
    footerDescription:
      "Travaux de renovation interieure, reprise de second oeuvre, menuiserie, peinture et petites reparations.",
    location: "Saint-Paul, La Reunion",
    limitDate: "2026-06-12T00:00:00Z",
    displayPrice: "250 000 EUR HT estimatif",
    price: 250000,
    lot: 3,
    duration: 6,
    reference: "DATA-2026-2031",
    sigleReference: "DATA-2031",
    buyer: "Commune de l'Ouest",
    avisLink: "https://www.data.gouv.fr/",
    typeMarket: "BTP",
    tags: ["travaux, renovation, batiment"],
    createdAt: "2026-04-25T08:00:00Z",
  },
  {
    id: "tender-4",
    title: "Nettoyage et entretien de locaux",
    description:
      "Nettoyage courant, entretien des sols et vitreries, interventions regulieres en milieu administratif.",
    footerDescription:
      "Nettoyage courant, entretien des sols et vitreries, interventions regulieres en milieu administratif.",
    location: "Mamoudzou, Mayotte",
    limitDate: "2026-06-05T00:00:00Z",
    displayPrice: "45 000 EUR HT estimatif",
    price: 45000,
    lot: 1,
    duration: 12,
    reference: "DATA-2026-2040",
    sigleReference: "DATA-2040",
    buyer: "Syndicat intercommunal",
    avisLink: "https://www.data.gouv.fr/",
    typeMarket: "Nettoyage",
    tags: ["nettoyage, entretien, locaux"],
    createdAt: "2026-04-28T08:00:00Z",
  },
  {
    id: "tender-5",
    title: "Maintenance preventive et corrective",
    description:
      "Maintenance des installations techniques, interventions preventive et corrective sur site.",
    footerDescription:
      "Maintenance des installations techniques, interventions preventive et corrective sur site.",
    location: "Dzaoudzi, Mayotte",
    limitDate: "2026-06-18T00:00:00Z",
    displayPrice: "85 000 EUR HT estimatif",
    price: 85000,
    lot: 2,
    duration: 18,
    reference: "DATA-2026-2052",
    sigleReference: "DATA-2052",
    buyer: "Etablissement public",
    avisLink: "https://www.data.gouv.fr/",
    typeMarket: "Maintenance",
    tags: ["maintenance, technique, preventif"],
    createdAt: "2026-05-02T08:00:00Z",
  },
  {
    id: "tender-6",
    title: "Prestations de transport et logistique",
    description:
      "Transport de materiels, logistique evenementielle et prestations associees.",
    footerDescription:
      "Transport de materiels, logistique evenementielle et prestations associees.",
    location: "Cayenne, Guyane",
    limitDate: "2026-06-30T00:00:00Z",
    displayPrice: "120 000 EUR HT estimatif",
    price: 120000,
    lot: 1,
    duration: 12,
    reference: "DATA-2026-2067",
    sigleReference: "DATA-2067",
    buyer: "Communaute d'agglomeration",
    avisLink: "https://www.data.gouv.fr/",
    typeMarket: "Transport",
    tags: ["transport, logistique, evenement"],
    createdAt: "2026-05-04T08:00:00Z",
  },
];
