export const cards = [
    {
        badge: "Auto-entrepreneur",
        price: 149,
        currency: "€",
        description: "Idéal pour démarrer rapidement votre activité",
        subtitle: "Création simple avec accompagnement administratif",
        buttonLabel: "Choisir Auto-entrepreneur",
        features: [
        { label: "Vérification des pièces du dossier", included: true },
        { label: "Accompagnement pour la saisie du dossier (INPI)", included: true },
        { label: "Préparation de la déclaration d’activité", included: true },
        { label: "Dépôt du dossier d’immatriculation", included: true },
        { label: "Suivi jusqu’au SIREN / SIRET", included: true },
        { label: "Accompagnement par un conseiller", included: true }
        ],
    },
    {
        badge: "SARL/EURL",
        price: 399,
        currency: "€",
        description: "La forme juridique la plus courante",
        subtitle: "Création complète avec accompagnement juridique",
        buttonLabel: "Choisir SARL/EURL",
        isPopular: true,
        features: [
        { label: "Rédaction des statuts", included: true },
        { label: "Déclaration de non-condamnation et filiation", included: true },
        { label: "Pouvoir (si nécessaire)", included: true },
        { label: "Annonce légale (préparation / accompagnement)", included: true },
        { label: "Accompagnement pour la saisie du dossier", included: true },
        { label: "Accompagnement pour la création du compte bancaire", included: true },
        { label: "Accompagnement pour le dépôt de capital", included: true },
        { label: "Dépôt du dossier (INPI / Greffe)", included: true },
        { label: "Suivi par un juriste", included: true },
        ],
    },
    {
        badge: "SAS/SASU",
        price: 449,
        currency: "€",
        description: "Flexible et évolutive pour développer votre projet",
        subtitle: "Solution moderne avec formalités complètes",
        buttonLabel: "Choisir SAS/SASU",
        features: [
        { label: "Rédaction des statuts personnalisés", included: true },
        { label: "Déclaration de non-condamnation et filiation", included: true },
        { label: "Pouvoir (si nécessaire)", included: true },
        { label: "Annonce légale (préparation / accompagnement)", included: true },
        { label: "Accompagnement pour la saisie du dossier", included: true },
        { label: "Accompagnement pour la création du compte bancaire", included: true },
        { label: "Accompagnement pour le dépôt de capital", included: true },
        { label: "Dépôt du dossier (INPI / Greffe)", included: true },
        { label: "Accompagnement juridique dédié", included: true },
        ],
    },
];